## listener.py
## Listener of blockchain for the orders generated by the ERP simulator

from web3 import Web3
import json
import sys
import os
import time
from config import CONTRACT_ADDRESS, RPC_URL

# Get the absolute path of the current file
current_file = os.path.abspath(__file__)
integration_dir = os.path.dirname(current_file)
project_dir = os.path.dirname(integration_dir)

# Correct path to the ABI
abi_path = os.path.join(project_dir, "blockchain", "artifacts", "contracts", "inventoryDRO.sol", "inventoryDRO.json")

print(f"=== DEBUG ===")
print(f"Current file: {current_file}")
print(f"Integration dir: {integration_dir}")
print(f"Project dir: {project_dir}")
print(f"ABI path: {abi_path}")
print(f"ABI exists: {os.path.exists(abi_path)}")
print(f"=============\n")

# Check if the file exists
if not os.path.exists(abi_path):
    print(f"❌ Error: ABI file not found")
    print(f"Searched path: {abi_path}")
    
    # Search for the file manually
    print("\nSearching for ABI files...")
    for root, dirs, files in os.walk(project_dir):
        for file in files:
            if file == "inventoryDRO.json":
                full_path = os.path.join(root, file)
                print(f"✅ Found at: {full_path}")
    sys.exit(1)

# Add the project directory to the path
sys.path.insert(0, project_dir)

# Import generate_order
try:
    from integration.orders.order_generator import generate_order
    print("✅ generate_order imported successfully")
except Exception as e:
    print(f"❌ Error importing generate_order: {e}")
    sys.exit(1)

# Connect to blockchain
w3 = Web3(Web3.HTTPProvider(RPC_URL))

if not w3.is_connected():
    print("❌ Error: Could not connect to blockchain")
    sys.exit(1)

# Contract address
contract_address = CONTRACT_ADDRESS

# Load ABI
with open(abi_path, 'r') as f:
    contract_json = json.load(f)
    abi = contract_json["abi"]

contract = w3.eth.contract(address=contract_address, abi=abi)

print("✅ System ready")
print(f"Current block: {w3.eth.block_number}")
print("Listening for events...\n")

# Initial block
last_block = w3.eth.block_number
processed_txs = set()

while True:
    try:
        current_block = w3.eth.block_number

        if current_block > last_block:
            print(f"New blocks: {last_block + 1} -> {current_block}")

            # Get event logs for both events
            logs_po = contract.events.PurchaseOrderTriggered().get_logs(
                from_block=last_block + 1,
                to_block=current_block
            )

            logs_alert = contract.events.Alert().get_logs(
                from_block=last_block + 1,
                to_block=current_block
            )

            # Process purchase orders
            for event in logs_po:
                tx_hash = event['transactionHash'].hex()
                if tx_hash not in processed_txs:
                    processed_txs.add(tx_hash)
                    print("🟢 AUTOMATIC PURCHASE ORDER")
                    quantity = event['args']['quantity']
                    print(f"Quantity: {quantity}")
                    generate_order(quantity)
            
            # Process alerts
            for event in logs_alert:
                tx_hash = event['transactionHash'].hex()
                if tx_hash not in processed_txs:
                    processed_txs.add(tx_hash)
                    print("🔴 ALERT")
                    message = event['args']['message']
                    print(f"Message: {message}")
            
            last_block = current_block

        time.sleep(2)

    except KeyboardInterrupt:
        print("\n🛑 Stopped")
        break
    except Exception as e:
        print(f"Error: {e}")
        time.sleep(5)